service: iot-service

plugins: 
  - serverless-dynamodb-local
  - serverless-offline

custom:
  serverless-offline:
    httpPort: 8080
    lambdaPort: 8082
  dynamodb:
    start:
      port: 8000
      inMemory: true
      migrate: true
      seed: true
    seed:
      development:
        sources:
          - table: device
            sources: [./db/device.json]
          - table: exception
            sources: [./db/exception.json]
          - table: cond
            sources: [./db/cond.json]
          - table: scene
            sources: [./db/scene.json]
          - table: user
            sources: [./db/user.json]
          - table: history
            sources: [./db/history.json]

provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-1
  stage: dev
  environment:
    DYNAMODB_TABLE: ${self:service}-${opt:stage, self:provider.stage}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.DYNAMODB_TABLE}"

functions:
  hello:
    handler: srv/handler.hello
    events:
      - http:
          path: hello
          method: get
          cors: true
  addDevice:
    handler: srv/deviceHandler.addDevice
    events:
      - http:
          path: addDevice
          method: post
          cors: true
  batchAddDevice:
    handler: srv/deviceHandler.batchAddDevice
    events:
      - http:
          path: batchAddDevice
          method: post
          cors: true
  queryDeviceList:
    handler: srv/deviceHandler.queryDeviceList
    events:
      - http:
          path: queryDeviceList
          method: get
          cors: true
  queryDeviceTypeList:
    handler: srv/deviceHandler.queryDeviceTypeList
    events:
      - http:
          path: queryDeviceTypeList
          method: get
          cors: true
  queryDeviceListByType:
    handler: srv/deviceHandler.queryDeviceListByType
    events:
      - http:
          path: queryDeviceListByType
          method: get
          cors: true
  deleteDevice:
    handler: srv/deviceHandler.deleteDevice
    events:
      - http:
          path: deleteDevice
          method: delete
          cors: true
  controlDevice:
    handler: srv/deviceHandler.controlDevice
    events:
      - http:
          path: controlDevice
          method: put
          cors: true
  queryExceptionList:
    handler: srv/exceptionHandler.queryExceptionList
    events:
      - http:
          path: queryExceptionList
          method: get
          cors: true 
  queryDeviceExceptionList:
    handler: srv/exceptionHandler.queryDeviceExceptionList
    events:
      - http:
          path: queryDeviceExceptionList
          method: get
          cors: true 
  updateException:
    handler: srv/exceptionHandler.updateException
    events:
      - http:
          path: updateException
          method: post
          cors: true 
  deleteException:
    handler: srv/exceptionHandler.deleteException
    events:
      - http:
          path: deleteException
          method: delete
          cors: true         
  addException:
    handler: srv/exceptionHandler.addException
    events:
      - http:
          path: addException
          method: post
          cors: true
  queryCondTypeList:
    handler: srv/condHandler.queryCondTypeList
    events:
      - http:
          path: queryCondTypeList
          method: get
          cors: true
  queryCondList:
    handler: srv/condHandler.queryCondList
    events:
      - http:
          path: queryCondList
          method: get
          cors: true
  querySceneBySN:
    handler: srv/sceneHandler.querySceneBySN
    events:
      - http:
          path: querySceneBySN
          method: get
          cors: true
  querySceneListByType:
    handler: srv/sceneHandler.querySceneListByType
    events:
      - http:
          path: querySceneListByType
          method: get
          cors: true
  querySceneList:
    handler: srv/sceneHandler.querySceneList
    events:
      - http:
          path: querySceneList
          method: get
          cors: true
  addScene:
    handler: srv/sceneHandler.addScene
    events:
      - http:
          path: addScene
          method: post
          cors: true
  updateScene:
    handler: srv/sceneHandler.updateScene
    events:
      - http:
          path: updateScene
          method: post
          cors: true
  updateSceneUsing:
    handler: srv/sceneHandler.updateSceneUsing
    events:
      - http:
          path: updateSceneUsing
          method: post
          cors: true
  deleteScene:
    handler: srv/sceneHandler.deleteScene
    events:
      - http:
          path: deleteScene
          method: delete
          cors: true
  queryUserList:
    handler: srv/userHandler.queryUserList
    events:
      - http:
          path: queryUserList
          method: get
          cors: true
  addUser:
      handler: srv/userHandler.addUser
      events:
        - http:
            path: addUser
            method: post
            cors: true
  deleteUser:
        handler: srv/userHandler.deleteUser
        events:
          - http:
              path: deleteUser
              method: delete
              cors: true
  queryHistoryList:
        handler: srv/historyHandler.queryHistoryList
        events:
          - http:
              path: queryHistoryList
              method: get
              cors: true
  queryHistoryListByDevice:
        handler: srv/historyHandler.queryHistoryListByDevice
        events:
          - http:
              path: queryHistoryListByDevice
              method: get
              cors: true
  deleteHistory:
        handler: srv/historyHandler.deleteHistory
        events:
          - http:
              path: deleteHistory
              method: delete
              cors: true
  queryHistoryByDate:
    handler: srv/historyHandler.queryHistoryByDate
    events:
      - http:
          path: queryHistoryByDate
          method: get
          cors: true

resources:
  Resources:
    DeviceDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          - AttributeName: serialNumber
            AttributeType: S
        KeySchema:
          - AttributeName: serialNumber
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: device
    ExceptionDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          - AttributeName: exceptionId
            AttributeType: S
        KeySchema:
          - AttributeName: exceptionId
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: exception
    CondDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          - AttributeName: serialNumber
            AttributeType: S
        KeySchema:
          - AttributeName: serialNumber
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: cond
    SceneDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          - AttributeName: serialNumber
            AttributeType: S
        KeySchema:
          - AttributeName: serialNumber
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: scene
    UserDynamoDbTable:
          Type: 'AWS::DynamoDB::Table'
          DeletionPolicy: Retain
          Properties:
            AttributeDefinitions:
              - AttributeName: userId
                AttributeType: S
            KeySchema:
              - AttributeName: userId
                KeyType: HASH
            ProvisionedThroughput:
              ReadCapacityUnits: 1
              WriteCapacityUnits: 1
            TableName: user
    HistoryDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          - AttributeName: historyId
            AttributeType: S
        KeySchema:
          - AttributeName: historyId
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: history
