service: iot-service

plugins: 
  - serverless-dynamodb-local
  - serverless-offline

custom:
  serverless-offline:
    httpPort: 8080
    lambdaPort: 8082
  dynamodb:
    start:
      port: 8000
      inMemory: true
      migrate: true
      seed: true
    seed:
      development:
        sources:
          - table: device
            sources: [./db/device.json]
          - table: exception
            sources: [./db/exception.json]
          - table: cond
            sources: [./db/cond.json]
          - table: scene
            sources: [./db/scene.json]

provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-1
  stage: dev
  environment:
    DYNAMODB_TABLE: ${self:service}-${opt:stage, self:provider.stage}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.DYNAMODB_TABLE}"

functions:
  hello:
    handler: srv/handler.hello
    events:
      - http:
          path: hello
          method: get
          cors: true
  addDevice:
    handler: srv/deviceHandler.addDevice
    events:
      - http:
          path: addDevice
          method: post
          cors: true
  batchAddDevice:
    handler: srv/deviceHandler.batchAddDevice
    events:
      - http:
          path: batchAddDevice
          method: post
          cors: true
  queryDeviceList:
    handler: srv/deviceHandler.queryDeviceList
    events:
      - http:
          path: queryDeviceList
          method: get
          cors: true
  queryDeviceTypeList:
    handler: srv/deviceHandler.queryDeviceTypeList
    events:
      - http:
          path: queryDeviceTypeList
          method: get
          cors: true
  queryDeviceListByType:
    handler: srv/deviceHandler.queryDeviceListByType
    events:
      - http:
          path: queryDeviceListByType
          method: get
          cors: true
  deleteDevice:
    handler: srv/deviceHandler.deleteDevice
    events:
      - http:
          path: deleteDevice
          method: delete
          cors: true
  controlDevice:
    handler: srv/deviceHandler.controlDevice
    events:
      - http:
          path: controlDevice
          method: put
          cors: true
  queryExceptionList:
    handler: srv/exceptionHandler.queryExceptionList
    events:
      - http:
          path: queryExceptionList
          method: get
          cors: true  
  addException:
    handler: srv/exceptionHandler.addException
    events:
      - http:
          path: addException
          method: post
          cors: true

resources:
  Resources:
    DeviceDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          - AttributeName: serialNumber
            AttributeType: S
        KeySchema:
          - AttributeName: serialNumber
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: device
    ExceptionDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          - AttributeName: exceptionId
            AttributeType: S
        KeySchema:
          - AttributeName: exceptionId
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: exception
    CondDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          - AttributeName: serialNumber
            AttributeType: S
        KeySchema:
          - AttributeName: serialNumber
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: cond
    SceneDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          - AttributeName: serialNumber
            AttributeType: S
        KeySchema:
          - AttributeName: serialNumber
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: scene
